version: 2

models:
  - name: stg_silverscreen__INVOICES
    description: "Staged invoices data (monthly rental cost details per movie and location) with standardized column names."

  - name: stg_silverscreen__MOVIE_CATALOGUE
    description: "Staged movie catalogue with core movie attributes used for joins and reporting."

  - name: stg_silverscreen__NJ_001
    description: "Staged ticket transactions for location NJ_001 (monthly grain)."

  - name: stg_silverscreen__NJ_002
    description: "Staged daily ticket sales for location NJ_002 (monthly grain)."

  - name: stg_silverscreen__NJ_003
    description: "Staged purchase-level data for location NJ_003 filtered to tickets (monthly grain)."

  - name: int_movie_costs
    description: "Intermediate model combining invoice rental costs with movie attributes (cost side)."
    columns:
      - name: movie_id
        description: "Unique movie identifier."
        tests:
          - not_null
      - name: month
        description: "Month for the rental invoice."
        tests:
          - not_null
      - name: location_id
        description: "Theatre location identifier."
        tests:
          - not_null

  - name: int_revenue
    description: "Intermediate model unifying monthly ticket sales and revenue across NJ_001, NJ_002, NJ_003."
    columns:
      - name: movie_id
        description: "Unique movie identifier."
        tests:
          - not_null
      - name: month
        description: "Transaction month."
        tests:
          - not_null
      - name: location_id
        description: "Theatre location identifier."
        tests:
          - not_null

  - name: cinema_profitability
    description: "Final mart table: monthly profitability inputs per movie and location (rental_cost vs ticket revenue)."
    columns:
      - name: movie_id
        description: "Unique movie identifier."
        tests:
          - not_null
      - name: month
        description: "Month of activity."
        tests:
          - not_null
      - name: location
        description: "Theatre location identifier."
        tests:
          - not_null
